name: LLMClient
options:
  bundleIdPrefix: com.evanchen
packages:
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: 2.4.0
targets:
  LLMClient:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: App
      - path: Models
      - path: Views
      - path: ViewModels
      - path: Services
      - path: Utilities
      - path: Resources
    dependencies:
      - package: MarkdownUI
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      DEVELOPMENT_TEAM: MNSNUB5U87
      CODE_SIGN_STYLE: Automatic
    info:
      path: Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        NSCameraUsageDescription: "We need access to your camera to take photos and attach them to the chat."
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
